# -*- coding: utf-8 -*-
"""Batch Transitions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rq6IwTnGsMsTaNb5MxsQW9KaIfk4vaMA
"""

# ===============================
# PCCW Batch Transitions (Multi-Batch Support)
# ===============================
import pandas as pd
import numpy as np
import os
from google.colab import files

# -------------------------------
# Load Form Responses
# -------------------------------
FORM_FILE = "pccw_form_responses.csv"
form_df = pd.read_csv(FORM_FILE)

# -------------------------------
# Helper: Column Detection
# -------------------------------
def find_contains_all(df, *subs):
    for c in df.columns:
        lc = c.lower()
        if all(s.lower() in lc for s in subs):
            return c
    return None

def find_prefix(df, prefix):
    for c in df.columns:
        if c.strip().lower().startswith(prefix.strip().lower()):
            return c
    return None

name_col   = find_contains_all(form_df, "name")
email_col  = find_contains_all(form_df, "email address")
role_col   = find_contains_all(form_df, "are you a/an")
capacity_col = find_contains_all(form_df, "how many mentees")

if email_col is None:
    raise ValueError("Could not automatically detect the email column in the form. Please check the form structure.")

# -------------------------------
# Load ALL matched_pairs*.csv files
# -------------------------------
matched_files = [
    f for f in os.listdir(".")
    if f.startswith("matched_pairs") and f.endswith(".csv")
]

if not matched_files:
    raise ValueError("No matched_pairs*.csv files were found. Please upload at least one matched_pairs CSV.")

matched_list = []
for fname in matched_files:
    df_m = pd.read_csv(fname)
    # Expecting columns including: Mentee_Email, Mentor_Email
    if "Mentee_Email" not in df_m.columns or "Mentor_Email" not in df_m.columns:
        raise ValueError(f"{fname} does not contain Mentee_Email or Mentor_Email columns.")
    matched_list.append(df_m)

matched_all = pd.concat(matched_list, ignore_index=True)

# Standardize emails to lowercase/stripped
matched_all["Mentee_Email"] = matched_all["Mentee_Email"].astype(str).str.strip().str.lower()
matched_all["Mentor_Email"] = matched_all["Mentor_Email"].astype(str).str.strip().str.lower()

matched_mentee_emails = set(matched_all["Mentee_Email"].dropna())
mentors_with_any_matches = set(matched_all["Mentor_Email"].dropna())

# -------------------------------
# Load mentors_remaining_capacity (latest)
# -------------------------------
cap_file = "mentors_remaining_capacity.csv"
cap_df = pd.read_csv(cap_file)

if "Email" not in cap_df.columns or "Remaining_Capacity" not in cap_df.columns:
    raise ValueError("mentors_remaining_capacity.csv must contain 'Email' and 'Remaining_Capacity' columns.")

cap_df["Email"] = cap_df["Email"].astype(str).str.strip().str.lower()
cap_df["Remaining_Capacity"] = cap_df["Remaining_Capacity"].fillna(0).astype(int)

cap_map = dict(zip(cap_df["Email"], cap_df["Remaining_Capacity"]))

# -------------------------------
# Process Form: Remove matched mentees, filter/update mentors
# -------------------------------
rows_out = []

for _, row in form_df.iterrows():
    email_val = str(row[email_col]).strip().lower() if pd.notna(row[email_col]) else ""
    role_raw  = str(row[role_col]).strip().lower() if role_col is not None else ""

    # Identify mentees vs mentors based on role
    is_mentee = ("undergraduate" in role_raw) or ("graduate" in role_raw)
    is_mentor = ("pccw" in role_raw)  # adjust if needed based on actual form wording

    # --- Mentees: drop if already matched in ANY previous batch ---
    if is_mentee:
        if email_val in matched_mentee_emails:
            # Already matched in some previous batch: exclude from next batch
            continue
        else:
            rows_out.append(row)
            continue

    # --- Mentors: filter by remaining capacity, update capacity field if known ---
    if is_mentor:
        remaining = cap_map.get(email_val, None)

        if remaining is not None:
            # Mentor appears in latest mentors_remaining_capacity.csv
            if remaining <= 0:
                # No remaining capacity: drop from next batch
                continue
            else:
                # Still has capacity: update their capacity answer to the remaining value
                if capacity_col is not None:
                    row[capacity_col] = str(remaining)
                rows_out.append(row)
                continue
        else:
            # Mentor not in cap_map; they might be new or unused so far.
            # If they HAVE been a mentor in matched_all but do not appear in cap_map,
            # treat them as fully used (0 capacity).
            if email_val in mentors_with_any_matches:
                # Previously used mentor with no remaining capacity record: drop
                continue
            else:
                # Completely new or never-matched mentor: keep their original capacity
                rows_out.append(row)
                continue

    # --- Everyone else (e.g., unknown role, admin test responses) ---
    rows_out.append(row)

next_form_df = pd.DataFrame(rows_out)

# -------------------------------
# Save and Download New Form Responses
# -------------------------------
output_file = "pccw_form_responses_next_batch.csv"
next_form_df.to_csv(output_file, index=False)

print(f"✅ Batch transition complete. New form responses saved to {output_file}.")
files.download(output_file)