# -*- coding: utf-8 -*-
"""Cleaned Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLl7VdKsII41pIsKJGiVe1jnEZ0fM_fK
"""

import pandas as pd
import numpy as np
import re
from pathlib import Path

# -------------------------------
# Load Data
# -------------------------------
file_path = "data/raw/demo_fake_data.csv"  
df = pd.read_csv(file_path)

# -------------------------------
# Controlled Vocabularies
# -------------------------------
CAREER_INTERESTS = [
    "Work-Life Balance", "Career Guidance", "Navigating The Workforce",
    "Public Service And Non-Profit Careers", "Entrepreneurship And Startup Advice",
    "International Student Guidance", "Transitioning From Academia To Industry Or Navigating Career Changes",
    "First Generation Student Guidance", "Networking"
]

LOCATIONS = [
    "East Coast U.S.", "West Coast U.S.", "NYC Area", "Western Europe", "Eastern Europe",
    "UK", "East Asia", "South Asia", "Other"
]

COLLEGES = [
    "College Of Agriculture And Life Sciences", "Charles H. Dyson School Of Applied Economics And Management",
    "College Of Architecture, Art, And Planning", "College Of Arts And Sciences",
    "Cornell SC Johnson College Of Business", "Nolan School Of Hotel Administration",
    "Dyson School Of Applied Economics And Management", "Cornell Ann S. Bowers College Of Computing And Information Science",
    "College Of Engineering", "College Of Human Ecology", "School Of Industrial And Labor Relations",
    "Cornell Jeb E. Brooks School Of Public Policy", "The Peter And Stephanie Nolan School Of Hotel Administration",
    "The Charles H. Dyson School Of Applied Economics And Management", "The Samuel Curtis Johnson Graduate School Of Management.",
    "Johnson Graduate School Of Management", "Cornell Tech (NYC)", "MBA", "LLM", "Cornell Law School",
    "School Of Veterinary Medicine", "Graduate School Field Of Study",
    "Sociology, Design And Environmental Analysis", "Literature, Archaeology, Religion, Culture",
    "City And Regional Planning, Government", "Weill Cornell Medicine (NYC)",
    "Weill Cornell Medicine-Qatar (Doha, Qatar)", "Weill Cornell Graduate School Of Medical Sciences (NYC)"
]

ORGANIZATIONS = [
    "GenEq - Gender Equity Resource Center", "Women's Leadership Initiative (WLI)",
    "First Gen", "Building Ourselves Through Sisterhood and Service (BOSS)",
    "Panhellenic/Multicultural Greek Fraternal Council",
    "Graduate and Professional Students Assembly (GPSA)",
    "Cornell Tech", "Other"
]

# -------------------------------
# Column Detection Helpers
# -------------------------------
def find_contains_all(*subs):
    for c in df.columns:
        lc = c.lower()
        if all(s.lower() in lc for s in subs):
            return c
    return None

def find_prefix(prefix):
    for c in df.columns:
        if c.strip().lower().startswith(prefix.strip().lower()):
            return c
    return None

# -------------------------------
# Detect Relevant Columns
# CHANGE TO REFLECT FORM CHANGES
# -------------------------------
name_col = find_contains_all("name")
email_col = find_contains_all("email address")
role_col = find_contains_all("are you a/an")
location_val_col = find_prefix("Your location/where you wish")
match_location_col = find_prefix("Would you like your match to be based, in part, on your location")
college_multi_col = find_prefix("Click all that apply")
match_college_col = find_prefix("Would you like your match to be based, in part, on your college")
career_col = find_contains_all("career advice areas")

# --- NEW BIO DETECTION LOGIC ---
BIO_QUESTION = "Please provide a short 1-2 sentences that we will use to introduce you to your mentor/mentee. (300 character limit)"

bio_col = None
# 1) Try exact match on full question text
for c in df.columns:
    if c.strip() == BIO_QUESTION:
        bio_col = c
        break

# 2) Fallback: look for distinctive phrase from the new question
if bio_col is None:
    bio_col = find_contains_all("introduce you to your mentor/mentee")

# 3) Legacy fallback: old wording ("short 1-2 sentences")
if bio_col is None:
    bio_col = find_contains_all("short 1-2 sentences")


notes_col = find_contains_all("anything else you would like to share")
phone_yes_col = find_contains_all("willing to provide", "cell phone")
phone_num_col = find_contains_all("please add your phone number")
student_level_col = find_contains_all("level of student")
field_cols = [c for c in df.columns if "field of interest/expertise" in c.lower()]

mentor_level_pref_col = find_contains_all("which level of student", "wish to mentor")
mentor_capacity_col = find_contains_all("how many mentees")

# Organization columns
org_primary_col = find_prefix("What organization are you affiliated with?")
org_grad_col = None
for c in df.columns:
    if c.strip().lower().startswith("what organization are you affiliated with?") and c != org_primary_col:
        org_grad_col = c
        break

# -------------------------------
# Helper Functions
# -------------------------------
def parse_rank(val):
    if isinstance(val, str):
        m = re.search(r'(\d+)', val)
        if m:
            i = int(m.group(1))
            if 1 <= i <= 5:
                return i
    return np.nan

def normalize_multiselect(val, reference_list):
    if not isinstance(val, str) or val.strip() == "":
        return ["None"]
    parts = re.split(r"[;,]", val)
    cleaned = []
    for p in parts:
        t = p.strip()
        if not t:
            continue
        t_title = t.title().replace("U.s.", "U.S.").replace("Nyc", "NYC")
        low = t_title.lower()
        match = None
        for ref in reference_list:
            if low in ref.lower() or ref.lower() in low:
                match = ref
                break
        cleaned.append(match if match else t_title)
    return cleaned if cleaned else ["None"]

def merge_organization_fields(row):
    vals = []
    if org_primary_col:
        v1 = str(row.get(org_primary_col, "")).strip()
        if v1:
            vals.append(v1)
    if org_grad_col:
        v2 = str(row.get(org_grad_col, "")).strip()
        if v2:
            vals.append(v2)
    if not vals:
        return ["None"]
    merged = ", ".join(vals)
    return normalize_multiselect(merged, ORGANIZATIONS)

# -------------------------------
# Clean and Process
# -------------------------------
clean = []
for _, row in df.iterrows():
    name = str(row.get(name_col, "None")).strip()
    email = str(row.get(email_col, "None")).strip()
    role_raw = str(row.get(role_col, "None")).strip().lower()

    if "pccw" in role_raw:
        role = "Mentor"; student_level = None
    elif "undergraduate" in role_raw:
        role = "Mentee"; student_level = "Undergraduate"
    elif "graduate" in role_raw:
        role = "Mentee"; student_level = "Graduate"
    else:
        role = "Unknown"; student_level = None

    # Field Selections
    fields = []
    for c in field_cols:
        v = row.get(c, "")
        if isinstance(v, str) and v.strip():
            rank = parse_rank(v)
            if not np.isnan(rank):
                label = re.findall(r"\[(.*?)\]", c)
                label = label[0] if label else c.split(" - ")[-1].strip()
                fields.append((int(rank), label))
    fields = sorted(fields, key=lambda x: x[0])[:5]
    ranked_fields = [f for _, f in fields] + ["None"] * (5 - len(fields))

    # Normalize lists
    location_vals = normalize_multiselect(row.get(location_val_col, "None"), LOCATIONS)
    match_loc = str(row.get(match_location_col, "")).strip().lower()
    if "no" in match_loc:
        location_vals = ["None"]

    college_vals = normalize_multiselect(row.get(college_multi_col, "None"), COLLEGES)
    match_college = str(row.get(match_college_col, "")).strip().lower()
    if "no" in match_college:
        college_vals = ["None"]

    career_vals = normalize_multiselect(row.get(career_col, "None"), CAREER_INTERESTS)
    org_vals = merge_organization_fields(row)

    # Phone / Bio / Notes
    willing_phone = str(row.get(phone_yes_col, "")).strip().lower()
    phone = str(row.get(phone_num_col, "None")).strip() if "yes" in willing_phone else "None"
    bio = str(row.get(bio_col, "None")).strip() if bio_col is not None else "None"
    notes = str(row.get(notes_col, "None")).strip()

    # Mentor-specific fields
    mentor_level_pref = str(row.get(mentor_level_pref_col, "None")).strip()
    mentor_capacity = str(row.get(mentor_capacity_col, "None")).strip()

    record = {
        "Name": name,
        "Role": role,
        "Student_Level": student_level,
        "Email": email,
        "Phone_Number": phone,
        "Organization": "|".join(org_vals),
        "Location": "|".join(location_vals),
        "College": "|".join(college_vals),
        "Career_Interests": "|".join(career_vals),
        "Field_1": ranked_fields[0],
        "Field_2": ranked_fields[1],
        "Field_3": ranked_fields[2],
        "Field_4": ranked_fields[3],
        "Field_5": ranked_fields[4],
        "Bio": bio,
        "Additional_Notes": notes,
        "Mentor_Level_Preferences": mentor_level_pref,
        "Mentor_Capacity": mentor_capacity
    }
    clean.append(record)

df_clean = pd.DataFrame(clean)

# -------------------------------
# Global unique naming (mentors + mentees together)
# -------------------------------
def make_unique(series):
    counts, out = {}, []
    for n in series:
        base = str(n).strip()
        counts[base] = counts.get(base, 0) + 1
        # First occurrence stays as-is; later ones get (2), (3), ...
        out.append(base if counts[base] == 1 else f"{base} ({counts[base]})")
    return out

df_clean["Name"] = make_unique(df_clean["Name"])

# -------------------------------
# Split Mentors / Mentees
# -------------------------------
mentors_df = df_clean[df_clean["Role"] == "Mentor"].reset_index(drop=True)
mentees_df = df_clean[df_clean["Role"] == "Mentee"].reset_index(drop=True)

# Remove Student_Level for mentors
mentors_df = mentors_df.drop(columns=["Student_Level"], errors="ignore")

# Reorder columns
mentor_cols = [
    "Name", "Role", "Email", "Phone_Number", "Organization",
    "Location", "College", "Career_Interests",
    "Field_1", "Field_2", "Field_3", "Field_4", "Field_5",
    "Bio", "Additional_Notes", "Mentor_Level_Preferences", "Mentor_Capacity"
]
mentee_cols = [
    "Name", "Role", "Student_Level", "Email", "Phone_Number", "Organization",
    "Location", "College", "Career_Interests",
    "Field_1", "Field_2", "Field_3", "Field_4", "Field_5",
    "Bio", "Additional_Notes"
]

mentors_df = mentors_df[mentor_cols]
mentees_df = mentees_df[mentee_cols]

# -------------------------------
# Save
# -------------------------------
OUTPUT_DIR = Path("data/cleaned")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
mentors_df.to_csv(OUTPUT_DIR / "mentors_clean.csv", index=False)
mentees_df.to_csv(OUTPUT_DIR /"mentees_clean.csv", index=False)

