# -*- coding: utf-8 -*-
"""Fields Similarity Scores Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_CzgKHhznav2NNqcmqmzfeS6P3Y-E8P
"""

import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# 1. Field list
# ------------------------------------------------------------
fields = [
    "Academia and research", "Architecture and urban planning",
    "Biotech, pharmaceutical, life sciences, and medical devices", "Business",
    "Consulting and strategy", "Corporate and general management", "Creative fields",
    "Data and analytics", "Design", "Education",
    "Energy, sustainability and the environment", "Engineering",
    "Entrepreneurship and startups", "Finance, investment and financial services",
    "Health and wellness", "Hospitality", "Human resources", "IT and technology",
    "Journalism, publishing and communications", "Law and legal services",
    "Marketing", "Media and entertainment", "Medicine and healthcare",
    "Non-profit and social enterprise", "Policy and advocacy",
    "Psychology and social work", "Public service and government",
    "Real estate", "Retail and consumer goods", "Veterinary medicine"
]

# ------------------------------------------------------------
# 2. Base matrix
# ------------------------------------------------------------
S = pd.DataFrame(0.15, index=fields, columns=fields)
for f in fields:
    S.loc[f, f] = 1.0

def set_pair(a, b, val):
    S.loc[a, b] = S.loc[b, a] = round(float(val), 2)

# ------------------------------------------------------------
# 3. Strong within-cluster pairs
# ------------------------------------------------------------
strong_within = {
    ("Business", "Finance, investment and financial services"): 0.95,
    ("Business", "Consulting and strategy"): 0.93,
    ("IT and technology", "Data and analytics"): 0.95,
    ("Medicine and healthcare", "Biotech, pharmaceutical, life sciences, and medical devices"): 0.95,
    ("Marketing", "Media and entertainment"): 0.93,
    ("Creative fields", "Design"): 0.93,
    ("Engineering", "Energy, sustainability and the environment"): 0.93,
    ("Academia and research", "Education"): 0.93,
}

# ------------------------------------------------------------
# 4. Cross-cluster bridges & weak ties (merged baseline)
# ------------------------------------------------------------
cross = {
    ("Business", "IT and technology"): 0.70,
    ("Business", "Data and analytics"): 0.72,
    ("Consulting and strategy", "Data and analytics"): 0.72,
    ("Consulting and strategy", "IT and technology"): 0.70,
    ("Corporate and general management", "IT and technology"): 0.65,
    ("Entrepreneurship and startups", "Design"): 0.70,
    ("Entrepreneurship and startups", "Marketing"): 0.70,
    ("Architecture and urban planning", "Design"): 0.75,
    ("Policy and advocacy", "Law and legal services"): 0.85,
    ("Non-profit and social enterprise", "Public service and government"): 0.80,
    ("Education", "Public service and government"): 0.65,
    ("Psychology and social work", "Public service and government"): 0.60,
    ("Journalism, publishing and communications", "Public service and government"): 0.60,
    ("Academia and research", "Data and analytics"): 0.70,
    ("Academia and research", "Engineering"): 0.68,
    ("Hospitality", "Retail and consumer goods"): 0.70,
    ("Hospitality", "Business"): 0.75,
    ("Human resources", "Corporate and general management"): 0.72,
    ("Real estate", "Finance, investment and financial services"): 0.80,
    ("Real estate", "Business"): 0.75,
}

weak = {
    ("Business", "Policy and advocacy"): 0.35,
    ("Business", "Public service and government"): 0.30,
    ("Data and analytics", "Education"): 0.48,
    ("IT and technology", "Education"): 0.45,
    ("Journalism, publishing and communications", "Marketing"): 0.50,
    ("Engineering", "Law and legal services"): 0.15,
    ("Finance, investment and financial services", "Public service and government"): 0.38,
    ("Medicine and healthcare", "Public service and government"): 0.15,
    ("Energy, sustainability and the environment", "Public service and government"): 0.50,
    ("Entrepreneurship and startups", "Policy and advocacy"): 0.45,
    ("Psychology and social work", "Law and legal services"): 0.50,
    ("Real estate", "Public service and government"): 0.28,
    ("Retail and consumer goods", "Marketing"): 0.50,
    ("Creative fields", "Business"): 0.30,
}

# ------------------------------------------------------------
# 5. Manual + tuned amendments
# ------------------------------------------------------------
manual = {
    # Academia
    ("Academia and research", "Biotech, pharmaceutical, life sciences, and medical devices"): 0.40,
    ("Academia and research", "Entrepreneurship and startups"): 0.20,
    ("Academia and research", "Non-profit and social enterprise"): 0.40,
    ("Academia and research", "Policy and advocacy"): 0.50,

    # Architecture
    ("Architecture and urban planning", "Consulting and strategy"): 0.20,
    ("Architecture and urban planning", "Energy, sustainability and the environment"): 0.40,
    ("Architecture and urban planning", "Engineering"): 0.20,
    ("Architecture and urban planning", "Real estate"): 0.20,
    ("Architecture and urban planning", "Policy and advocacy"): 0.20,
    ("Architecture and urban planning", "Public service and government"): 0.30,
    ("Architecture and urban planning", "Business"): 0.15,

    # Biotech / Pharma
    ("Biotech, pharmaceutical, life sciences, and medical devices", "Consulting and strategy"): 0.30,
    ("Biotech, pharmaceutical, life sciences, and medical devices", "Energy, sustainability and the environment"): 0.30,
    ("Biotech, pharmaceutical, life sciences, and medical devices", "Engineering"): 0.40,
    ("Biotech, pharmaceutical, life sciences, and medical devices", "Health and wellness"): 0.40,

    # Business
    ("Business", "Corporate and general management"): 0.75,
    ("Business", "Retail and consumer goods"): 0.60,
    ("Business", "Law and legal services"): 0.45,
    ("Business", "Human resources"): 0.60,
    ("Business", "Psychology and social work"): 0.15,

    # Consulting
    ("Consulting and strategy", "Finance, investment and financial services"): 0.70,

    # Data and analytics
    ("Data and analytics", "Human resources"): 0.20,
    ("Data and analytics", "Engineering"): 0.70,
    ("Data and analytics", "Finance, investment and financial services"): 0.65,
    ("Data and analytics", "Marketing"): 0.60,
    ("Data and analytics", "Health and wellness"): 0.50,

    # Design
    ("Design", "Business"): 0.40,
    ("Design", "IT and technology"): 0.70,
    ("Design", "Media and entertainment"): 0.60,
    ("Design", "Education"): 0.30,

    # Education
    ("Education", "Policy and advocacy"): 0.65,
    ("Education", "Health and wellness"): 0.20,

    # Finance
    ("Finance, investment and financial services", "Corporate and general management"): 0.65,
    ("Finance, investment and financial services", "IT and technology"): 0.60,
    ("Finance, investment and financial services", "Entrepreneurship and startups"): 0.60,

    # Journalism
    ("Journalism, publishing and communications", "Policy and advocacy"): 0.60,

    # Non-profit
    ("Non-profit and social enterprise", "Psychology and social work"): 0.75,
    ("Non-profit and social enterprise", "Health and wellness"): 0.45,
    ("Non-profit and social enterprise", "Business"): 0.50,

    # Policy & Media
    ("Policy and advocacy", "Media and entertainment"): 0.15,

    # Public Service
    ("Public service and government", "Law and legal services"): 0.78,
    ("Public service and government", "Engineering"): 0.15,

    # Real Estate
    ("Real estate", "Engineering"): 0.15,
    ("Real estate", "Law and legal services"): 0.15,

    # Medicine
    ("Medicine and healthcare", "Education"): 0.15,
    ("Medicine and healthcare", "Policy and advocacy"): 0.15,

    # Veterinary cluster
    ("Veterinary medicine", "Medicine and healthcare"): 0.70,
    ("Veterinary medicine", "Biotech, pharmaceutical, life sciences, and medical devices"): 0.50,
    ("Veterinary medicine", "Education"): 0.40,
    ("Veterinary medicine", "Non-profit and social enterprise"): 0.50,
}

# ------------------------------------------------------------
# 6. Extremely unlikely pairs (0.05 floor)
# ------------------------------------------------------------
extremely_unlikely = [
    ("Engineering", "Creative fields"),
    ("Engineering", "Journalism, publishing and communications"),
    ("Engineering", "Psychology and social work"),
    ("IT and technology", "Veterinary medicine"),
    ("Data and analytics", "Veterinary medicine"),
    ("Energy, sustainability and the environment", "Media and entertainment"),

    ("Medicine and healthcare", "Architecture and urban planning"),
    ("Medicine and healthcare", "Creative fields"),
    ("Medicine and healthcare", "Finance, investment and financial services"),
    ("Medicine and healthcare", "Law and legal services"),
    ("Medicine and healthcare", "Marketing"),

    ("Law and legal services", "IT and technology"),
    ("Law and legal services", "Engineering"),
    ("Law and legal services", "Design"),
    ("Law and legal services", "Veterinary medicine"),

    ("Creative fields", "Biotech, pharmaceutical, life sciences, and medical devices"),
    ("Media and entertainment", "Biotech, pharmaceutical, life sciences, and medical devices"),
    ("Media and entertainment", "Veterinary medicine"),
    ("Journalism, publishing and communications", "Veterinary medicine"),

    ("Architecture and urban planning", "Medicine and healthcare"),
    ("Architecture and urban planning", "Law and legal services"),
    ("Real estate", "Medicine and healthcare"),
    ("Real estate", "Biotech, pharmaceutical, life sciences, and medical devices"),

    ("Retail and consumer goods", "Policy and advocacy"),
    ("Hospitality", "Engineering"),
    ("Hospitality", "Law and legal services"),

    ("Veterinary medicine", "Architecture and urban planning"),
    ("Veterinary medicine", "Law and legal services"),
    ("Veterinary medicine", "Policy and advocacy"),
    ("Veterinary medicine", "Marketing"),
]

# ------------------------------------------------------------
# 7. Apply all mappings
# ------------------------------------------------------------
for group in (strong_within, cross, weak, manual):
    for (a, b), v in group.items():
        set_pair(a, b, v)

# Apply 0.05 floor (except Retail–Biotech stays 0.15)
for a, b in extremely_unlikely:
    if {a, b} != {"Retail and consumer goods", "Biotech, pharmaceutical, life sciences, and medical devices"}:
        set_pair(a, b, 0.05)

# ------------------------------------------------------------
# 8. Save
# ------------------------------------------------------------
OUTPUT_DIR = Path("data/cleaned")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
S.to_csv(OUTPUT_DIR / "field_similarity_matrix.csv", index=False)
print(f"Shape: {S.shape}")
print(f"Mean off-diagonal similarity: {S.values[np.triu_indices_from(S, 1)].mean():.3f}")